Add director
albertleinsoo/java-filmorate pull request #11
Opened 2022-11-08 09:16 UTC by Killarayne

2022-11-08 11:02 UTC, alex-blag requested changes

2022-11-08 11:02 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public void delete(@Valid @PathVariable long id){
@Valid

2022-11-08 11:02 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/exeptions/DirectorIdExeption.java
> +public class DirectorIdExeption extends RuntimeException{
Что за ексепшн такой DirectorId, что с ним случилось? :-)

2022-11-08 11:02 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    private final DirectorDbStorage directorDbStorage;
DirectorStorage и DirectorDbStorage?

2022-11-08 11:02 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDbStorage.java
> +        if (jdbcTemplate.queryForObject(sql, Integer.class,directorId) != 1) {
Тут, полагаю, можно использовать COUNT(1)

2022-11-08 11:02 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorStorage.java
> +    Director getDirectorById(long directorId);
Предполагаю, что ревьюер тут попросит заменить на Optional<Director>

2022-11-08 11:02 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private final DirectorDbStorage directorDbStorage;
DirectorDbStorage размещать в FilmDbStorage неправильно.

2022-11-08 11:02 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private Film updateDirectors(Film film) {
Непонятно, что делает метод. Обновляет дирика или добавляет нового?

2022-11-08 11:02 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    List<Film> getDirectorFilmsSortedBy(long directorId, String sortBy);
Не уверен, но вроде лучше этот метод держать в DirectorStorage

Плюс, там запрашивать не сами фильмы, а иды фильмов этого режисера, а уже потом направлять иды в ФилмСторадж и по ним получать список фильмов.

2022-11-08 11:02 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    private String name;
Достаточно одно аннотации.

2022-11-08 12:08 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public List<Film> getDirectorFilmsSortedBy(long directorId, String sortBy) {
Функционал этого метода можно разбить на два метода, чтобы разделить ответственность и снизить логику и бардак в репо :-)

2022-11-08 13:37 UTC, Killarayne commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorStorage.java
> +    Director getDirectorById(long directorId);
у нас ни в одном интерфейсе нету Optional

2022-11-08 13:38 UTC, Killarayne commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public void delete(@Valid @PathVariable long id){
поправил

2022-11-08 13:38 UTC, Killarayne commented on src/main/java/ru/yandex/practicum/filmorate/exeptions/DirectorIdExeption.java
> +public class DirectorIdExeption extends RuntimeException{
поправил

2022-11-08 13:38 UTC, Killarayne commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private final DirectorDbStorage directorDbStorage;
исправлено

2022-11-08 13:39 UTC, Killarayne commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private Film updateDirectors(Film film) {
поменял название, добавил комментарий к методу

2022-11-08 13:39 UTC, Killarayne commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    private String name;
поправил

2022-11-08 14:32 UTC, VTimopheyev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public List<Film> getDirectorFilmsSortedBy(long directorId, String sortBy) {
Я бы тоже засунул в directorStorage, там кажется логичнее его держать. Насчет разбить на два - тоже согласен, но это в качестве опциональной правки, для повышения читабельности, имхо.

2022-11-08 14:42 UTC, VTimopheyev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public List<Film> getDirectorFilmsSortedBy(long directorId, String sortBy) {
Я бы разбил на два, имхо, для улучшения читабельности, а по реализации ничего проблемного не увидел

2022-11-08 14:49 UTC, Killarayne commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public List<Film> getDirectorFilmsSortedBy(long directorId, String sortBy) {
@VTimopheyev ты имеешь ввиду один метод на сортировку по лайкам, другой на сортировку по годам? c прежней сигнатурой метода?

2022-11-08 15:26 UTC, VTimopheyev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public List<Film> getDirectorFilmsSortedBy(long directorId, String sortBy) {
да, ну не вижу ничего страшного передавать сюда directorId

2022-11-09 10:18 UTC, VTimopheyev approved these changes

2022-11-09 11:48 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    List<Film> getDirectorFilmsSortedBy(long directorId, String sortBy);
Согласен, что в DirectorStorage этот метод будет уместнее

2022-11-09 12:34 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    List<Film> getDirectorFilmsSortedBy(long directorId, String sortBy);
По итогу встречи решили оставить так, как есть сейчас. Т.к. метод относится к эндпоинту фильмов
GET /films/director/{directorId}?sortBy=[year,likes]

2022-11-09 13:51 UTC, albertleinsoo reviewed
.DS_Store?

2022-11-09 13:58 UTC, alex-blag approved these changes

2022-11-09 14:03 UTC, merged