Add recommendations
albertleinsoo/java-filmorate pull request #14
Opened 2022-11-09 19:41 UTC by VTimopheyev

2022-11-09 20:00 UTC, alex-blag requested changes
По-моему ты в сервисе рукомендаций реализовал то, что можно (нужно) было сделать в дао лайков методами базы данных. Тут, как я понял, ты выгружаешь все в ява-код и обрабатываешь -- это приведет к перегонке от базы в бек кучу данных... :-)

2022-11-09 20:00 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +        //film_id, user_id
Забыл?

2022-11-09 20:00 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +<<<<<<< HEAD
Артефакты от мержа.

2022-11-09 20:00 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +<<<<<<< HEAD
Артефакты от мержа.

2022-11-09 20:00 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                //System.out.println("Like created: "+ Arrays.toString(like));
Мусорный комент?

2022-11-09 20:00 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    List<Long[]> getAllLikes();
По идее есть сущность лайков.

2022-11-09 20:33 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +    private List<Film> cookRecommendationList(List<Long[]> allLikes, Long userId) {
Имя метода makeRecommendationList, думаю, будет смотреться лучше)

2022-11-09 20:33 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +    private List<Film> cookRelevantFilmsList (List<Long> commonLikesUsers, List<Long> userLikes, List<Long[]> allLikes) {
Аналогично, cookRelevantFilmsList -> makeRelevantFilmsList

2022-11-09 20:33 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +        for (Long id : commonLikesUsers) {
Посмотри, можно ли циклы заменить на стримы?)
По типу:
_commonLikesUsers.stream()
   ...
   .collect(Collectors.toList());_

2022-11-09 20:33 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                //System.out.println("Like created: "+ Arrays.toString(like));
Желательно убрать ненужный код, чтобы ревьюер не заставил прибирать)
Или вместо вывода в строку добавить в лог

2022-11-10 07:35 UTC, VTimopheyev commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +        //film_id, user_id
Ага

2022-11-10 07:38 UTC, VTimopheyev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    List<Long[]> getAllLikes();
Нет такой сущности, никто не создавал, ну и мне она показалась ненужной

2022-11-10 07:39 UTC, VTimopheyev commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +    private List<Film> cookRecommendationList(List<Long[]> allLikes, Long userId) {
Можно и make) на вкус и цвет все фломастеры разные;))

2022-11-10 07:43 UTC, VTimopheyev commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +    private List<Film> cookRelevantFilmsList (List<Long> commonLikesUsers, List<Long> userLikes, List<Long[]> allLikes) {
Ага

2022-11-10 07:46 UTC, VTimopheyev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +<<<<<<< HEAD
ну комментарии не мои, я их не стал трогать

2022-11-10 07:46 UTC, VTimopheyev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +<<<<<<< HEAD
а этот мусор просмотрел, да

2022-11-10 07:47 UTC, VTimopheyev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                //System.out.println("Like created: "+ Arrays.toString(like));
ага

2022-11-10 07:48 UTC, VTimopheyev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                //System.out.println("Like created: "+ Arrays.toString(like));
Уберу, ага, это от отладки осталось

2022-11-10 07:52 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +<<<<<<< HEAD
<<<<<<< HEAD -- это не комментарий, а мусор от кривого мержа :-) не знаю, кто оставил, но если есть у тебя, удаляй смело. 

И если что-то исправляешь, исправил, добавил код, то потом тут нажми кнопку Resolve conversation, поможет ориентироваться.

2022-11-10 07:55 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    List<Long[]> getAllLikes();
Ну по идее сущность тебе нужна, я обозначил -- исправишь или нет, по желанию, -- потом уже от курсового ревьюера конечное решение услышишь.

2022-11-10 08:43 UTC, VTimopheyev commented
> По-моему ты в сервисе рукомендаций реализовал то, что можно (нужно) было сделать в дао лайков методами базы данных. Тут, как я понял, ты выгружаешь все в ява-код и обрабатываешь -- это приведет к перегонке от базы в бек кучу данных... :-)

К базе у меня два запроса: 
1. Забираю одну таблицу и перегоняю ее в коллекцию
2. Прихожу с айдишниками фильмов и получаю итоговый список нужных фильмов. 

Насколько я понимаю, хороший вариант - это именно минимум обращений к базе. Можешь глянуть пример реализации, его предлагали в ТЗ: https://github.com/eugenp/tutorials/blob/master/algorithms-modules/algorithms-miscellaneous-2/src/main/java/com/baeldung/algorithms/slope_one/SlopeOne.java 

Там все делается, насколько можно судить, именно на уровне сервиса

2022-11-10 08:45 UTC, VTimopheyev commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +        for (Long id : commonLikesUsers) {
Уверен, что можно, но зачем? Опять-таки вот пример из ТЗ, циклов никто не стесняется:
https://github.com/eugenp/tutorials/blob/master/algorithms-modules/algorithms-miscellaneous-2/src/main/java/com/baeldung/algorithms/slope_one/SlopeOne.java

2022-11-10 08:51 UTC, VTimopheyev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +<<<<<<< HEAD
Ну я вот это имел в виду:

2022-11-10 08:55 UTC, alex-blag commented
> 
> К базе у меня два запроса:
> 
> 1. Забираю одну таблицу и перегоняю ее в коллекцию
> 2. Прихожу с айдишниками фильмов и получаю итоговый список нужных фильмов.
> 
> Насколько я понимаю, хороший вариант - это именно минимум обращений к базе. Можешь глянуть пример реализации, его предлагали в ТЗ: https://github.com/eugenp/tutorials/blob/master/algorithms-modules/algorithms-miscellaneous-2/src/main/java/com/baeldung/algorithms/slope_one/SlopeOne.java
> 
> Там все делается, насколько можно судить, именно на уровне сервиса

Смотри, ты вызываешь:

List<Long[]> allLikes = filmStorage.getAllLikes();

а теперь представь, что у тебя реальная система, тысячи пользователей и сотни тысяч лайков, а ты ВСЁ грузишь в ява-скоуп :-) Т.е. ты занимаешь двойной объем памяти одними и теми же данными.

С точки зрения обычной логики, тебе надо произвести операции с данными как можно ближе к данным, без дублирования. Т.е. лучше послать sql запрос, например, чтобы получить необходимые иды фильмов. А с ними уже запросить необходимые фильмы.

ПС: у меня не было времени, чтобы углубиться в фичу, но я предполагаю, что ты можешь получить иды фильмов из одной таблицы FILM_LIKES.

2022-11-10 08:56 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +<<<<<<< HEAD
А, ну да, это комментарий хороший :-))

2022-11-10 08:59 UTC, VTimopheyev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    List<Long[]> getAllLikes();
А почему ты считаешь, что нужна?

2022-11-10 09:00 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    List<Long[]> getAllLikes();
Внизу комменты смотри, если надо проговорить общо -- в слак :-)

2022-11-10 10:26 UTC, VTimopheyev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    List<Long[]> getAllLikes();
Обсудили в слаке, решили что это задача "на потом"

2022-11-10 11:07 UTC, alex-blag approved these changes

2022-11-10 15:30 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +        for (Long id : commonLikesUsers) {
Просто меня наш ревьюер просила переделать. Тогда на её усмотрение)

2022-11-10 15:34 UTC, albertleinsoo approved these changes

2022-11-10 15:34 UTC, merged