Add search
albertleinsoo/java-filmorate pull request #16
Opened 2022-11-11 21:08 UTC by albertleinsoo

Поиск фильмов по названию и режиссёрам

2022-11-12 11:48 UTC, alex-blag requested changes

2022-11-12 11:48 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> searchFilmsByTitleDirector(@RequestParam String query, @RequestParam String by) {
Можешь попробовать вместо "String by" использовать List или Set, будет удобнее.

2022-11-12 11:48 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/exeptions/FilmSearchByTitleDirectorException.java
> +public class FilmSearchByTitleDirectorException extends RuntimeException {
Так а ошибка-то в чем?

2022-11-12 11:48 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (by.equals("title") || by.equals("director") || by.equals("title,director") || by.equals("director,title")) {
Если будет не "String by", а List или Set проверять будет удобнее.

2022-11-12 11:48 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                                            ")) LIKE UPPER('%" + query + "%')" +
А попробовал?

String sqlParam = "%" + query + "%";
LIKE UPPER(?)

2022-11-12 14:27 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/exeptions/FilmSearchByTitleDirectorException.java
> +public class FilmSearchByTitleDirectorException extends RuntimeException {
Передаётся в сообщении

2022-11-12 14:29 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                                            ")) LIKE UPPER('%" + query + "%')" +
Не понимаю различия между этими конструкциями. Что так я делаю SQL инъекцию вставляя String query, что String sqlParam = "%" + query + "%";

2022-11-12 15:05 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                                            ")) LIKE UPPER('%" + query + "%')" +
Полагаю, что тут <LIKE UPPER('%" + query + "%')"> -- возможна инъекция.
А тут <LIKE UPPER(?)> -- нет.

2022-11-12 15:06 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/exeptions/FilmSearchByTitleDirectorException.java
> +public class FilmSearchByTitleDirectorException extends RuntimeException {
И называние эксепшена должно указывать ошибку :-) Иначе мог бы назвать просто Exception

2022-11-12 17:38 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/exeptions/FilmSearchByTitleDirectorException.java
> +public class FilmSearchByTitleDirectorException extends RuntimeException {
Название ошибки поиска стало более говорящим

2022-11-12 17:39 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (by.equals("title") || by.equals("director") || by.equals("title,director") || by.equals("director,title")) {
Согласен, исправил

2022-11-12 17:39 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                                            ")) LIKE UPPER('%" + query + "%')" +
Параметр запроса изменён на:
String sqlParam = "'%" + query + "%'";

2022-11-12 18:12 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (by.equals("title") || by.equals("director") || by.equals("title,director") || by.equals("director,title")) {
Согласен, поправил

2022-11-12 18:32 UTC, alex-blag requested changes

2022-11-12 18:32 UTC, alex-blag commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    //private final NamedParameterJdbcTemplate = new NamedParameterJdbcTemplate(jdbcTemplate);
-

2022-11-12 23:32 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    //private final NamedParameterJdbcTemplate = new NamedParameterJdbcTemplate(jdbcTemplate);
.

2022-11-13 07:02 UTC, alex-blag approved these changes

2022-11-14 05:25 UTC, sergej-d83 approved these changes

2022-11-14 12:10 UTC, isalamatov approved these changes

2022-11-14 13:22 UTC, merged