Add reviews
albertleinsoo/java-filmorate pull request #5
Opened 2022-11-05 17:36 UTC by isalamatov

2022-11-05 19:28 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private final ReviewDbStorage reviewDbStorage;
Думаю, тип хорошо заменить ReviewDbStorage на ReviewStorage, как у нас в FilmService

2022-11-05 19:28 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public ReviewService(ReviewDbStorage reviewDbStorage) {
В конструкторе, соостветственно, тоже идёт ReviewStorage

2022-11-05 19:28 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (review.getUserId() == 0 || review.getFilmId() == 0) {
Возможно эти проверки можно перенести в ReviewDbStorage, чтобы не надо было добавлять check методы в интерфейс?

2022-11-05 19:28 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +    public boolean checkReview(Review review) {
Если будем использовать checkReview только в ReviewDbStorage, то стоит сделать эти метода private

2022-11-06 05:56 UTC, isalamatov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private final ReviewDbStorage reviewDbStorage;
Замечание принимается, исправлено.

2022-11-06 05:56 UTC, isalamatov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public ReviewService(ReviewDbStorage reviewDbStorage) {
Замечание принимается, исправлено.

2022-11-06 05:57 UTC, isalamatov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (review.getUserId() == 0 || review.getFilmId() == 0) {
Если я правильно понял архитектурный подход - все проверки данных и бизнес-логика делаются на уровне сервиса. Поэтому логично было бы их оставить. Если ошибаюсь - просьба скинуть ссылку на какие-то материалы по архитектуре, чтобы откорректировать представления.

2022-11-06 05:59 UTC, isalamatov commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +    public boolean checkReview(Review review) {
Ок, исправлено.

2022-11-06 09:26 UTC, albertleinsoo commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (review.getUserId() == 0 || review.getFilmId() == 0) {
У нас сервис поидее должен иметь возможность работать с любой реализацией ReviewStorage. И в другой реализации проверки могут быть реализованы по другому.
А сами методы проверок, как понимаю, не логично выносить в интерфейс. Ведь они уже подразумевают, как мы реализовываем функционал, а не сами методы функционала.
Но сейчас можно оставить так, а если скажут что, тогда и переделаем)

2022-11-06 09:27 UTC, albertleinsoo approved these changes

2022-11-06 10:13 UTC, alex-blag approved these changes
Некоторые моменты проговорим в слаке.

2022-11-06 10:44 UTC, alex-blag commented
Уточните, ветка направлена в main, должно идти в develop.

2022-11-06 10:52 UTC, alex-blag requested changes
Уточните, add-reviews ветка направлена в main, должно идти в develop.

2022-11-06 11:06 UTC, alex-blag approved these changes

2022-11-06 11:35 UTC, merged